// Browser-local recovery: map data lives in IndexedDB, small view state in localStorage.
'use strict';
let sessionRestoring=true,sessionRevision=-1,sessionWriting=false,sessionBinding='';
let sessionDocumentId=crypto.randomUUID();
const sessionKey='aether-atlas-editor-view';
function sessionDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('aether-atlas-session',1);request.onupgradeneeded=()=>request.result.createObjectStore('sessions');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function sessionRecord(value){const db=await sessionDatabase();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('sessions',value===undefined?'readonly':'readwrite'),store=tx.objectStore('sessions'),request=value===undefined?store.get('editor'):store.put(value,'editor');tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
function sessionView(){return{documentId:sessionDocumentId,camera:{yaw,tilt,roll,relief,zoom,ox:ox/$('viewport').clientWidth,oy:oy/$('viewport').clientHeight},flatRegion,flatCamera,submapId:submapEdit?.patch.id||null,active,grid,spin:planetGuide.spinning,tool,waterColor:$('lakeColor')?.value};}
function saveSessionView(){if(sessionRestoring)return;try{localStorage.setItem(sessionKey,JSON.stringify(sessionView()));}catch{}}
async function saveEditorSession(){const binding=JSON.stringify({documentId:sessionDocumentId,drive:driveFileId,cloud:window.atlasAccountContext?.()});if(sessionRestoring||sessionWriting||!layers.length||(sessionRevision===driveRevision&&sessionBinding===binding))return;sessionWriting=true;const revision=driveRevision;try{await sessionRecord({documentId:sessionDocumentId,project:projectData(),view:sessionView(),drive:{id:driveFileId,current:driveCurrent},cloud:window.atlasAccountContext?.()});sessionRevision=revision;sessionBinding=binding;}catch(error){$('saved').textContent='Não foi possível guardar a sessão neste navegador. Exporte o JSON.';console.warn('Falha ao guardar sessão local:',error.name);}finally{sessionWriting=false;}}
window.atlasSessionReady=(async()=>{try{const saved=await sessionRecord();if(!saved?.project)return;sessionDocumentId=saved.documentId||crypto.randomUUID();const revision=driveRevision;const result=await $('file').onchange({target:{files:[new File([JSON.stringify(saved.project)],'sessao.json',{type:'application/json'})],value:''},discardConfirmed:true,canApply:()=>driveRevision===revision});if(!result)return;let view=saved.view;try{const stored=JSON.parse(localStorage.getItem(sessionKey)||'null');if(stored?.documentId===sessionDocumentId)view=stored;}catch{}if(view?.submapId){const patch=patches.find(p=>p.id===view.submapId);if(patch)await enterSubmap(patch);}if(view?.flatRegion)enterFlatRegion(view.flatRegion);if(view?.flatCamera)flatCamera=view.flatCamera;
 const c=view?.camera;if(c&&['yaw','tilt','roll','relief','zoom','ox','oy'].every(k=>Number.isFinite(c[k]))){({yaw,tilt,roll,relief,zoom}=c);ox=c.ox*$('viewport').clientWidth;oy=c.oy*$('viewport').clientHeight;}
 active=Math.max(0,Math.min(layers.length-1,view?.active||0));grid=!!view?.grid;$('grid').classList.toggle('active',grid);if(view?.waterColor&&/^#[0-9a-f]{6}$/i.test(view.waterColor))$('lakeColor').value=view.waterColor;document.querySelector(`[data-tool="${view?.tool||'pan'}"]`)?.click();planetGuide.setSpinning(!!view?.spin);render();draw();window.atlasSessionCloud=saved.cloud||null;if(saved.drive?.id){driveFileId=saved.drive.id;driveCurrent=saved.drive.current;driveLocalProject=false;updateDriveUI();}window.atlasSessionRestored=true;$('saved').textContent='Sessão local recuperada';notify('Mapa e posição recuperados neste navegador.');
 }catch(error){console.warn('Falha ao recuperar sessão local:',error.name);}finally{sessionRestoring=false;}})();
setInterval(saveSessionView,500);setInterval(saveEditorSession,2000);
window.addEventListener('pagehide',()=>{saveSessionView();saveEditorSession();});
document.addEventListener('visibilitychange',()=>{if(document.hidden){saveSessionView();saveEditorSession();}});

const sessionOpen=$('file').onchange;
$('file').onchange=async e=>{const opened=await sessionOpen(e);if(opened&&!sessionRestoring){sessionDocumentId=crypto.randomUUID();sessionRevision=-1;saveSessionView();saveEditorSession();}return opened;};
const sessionNew=$('new').onclick;
$('new').onclick=async e=>{const generation=driveGeneration;await sessionNew(e);if(generation!==driveGeneration){sessionDocumentId=crypto.randomUUID();sessionRevision=-1;saveSessionView();saveEditorSession();}};
