const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'../..');
test('editor and viewer have separate Android app identities with real PNG and maskable icons',()=>{
 const manifests=['editor','viewer'].map(name=>JSON.parse(fs.readFileSync(path.join(root,name+'.webmanifest'),'utf8')));assert.notEqual(manifests[0].id,manifests[1].id);
 for(const m of manifests){assert.equal(m.display,'standalone');assert(new URL(m.start_url,'https://example.test').pathname.startsWith(m.scope));for(const size of ['192x192','512x512'])assert(m.icons.some(i=>i.sizes===size&&i.purpose==='any'));assert(m.icons.some(i=>i.purpose==='maskable'));for(const icon of m.icons){const bytes=fs.readFileSync(path.join(root,icon.src));assert.equal(bytes.subarray(1,4).toString(),'PNG');const [w,h]=icon.sizes.split('x').map(Number);assert.equal(bytes.readUInt32BE(16),w);assert.equal(bytes.readUInt32BE(20),h);}}
});
function worker(){const events={},matches=[],requests=[],cache={match:async key=>{matches.push(key);return{offline:key};},addAll:async()=>{}};const context={URL,Response,fetch:async request=>{requests.push(request);throw Error('offline');},caches:{open:async()=>cache,keys:async()=>[],delete:async()=>true},self:{location:{origin:'https://example.test'},clients:{claim:async()=>{}},addEventListener:(name,handler)=>events[name]=handler}};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'sw.js'),'utf8').replace('/*__SHELL_ASSETS__*/[]',JSON.stringify(['/player.js','/index.html','/player.html'])),context);return{events,matches,requests};}
test('offline navigation preserves editor and viewer shells while APIs stay network-only',async()=>{
 const {events,matches}=worker();for(const [url,expected] of [['/?app=editor','/index.html'],['/play?share=abc','/player.html']]){let response;events.fetch({request:{method:'GET',url:'https://example.test'+url,mode:'navigate'},respondWith:p=>response=p});assert.deepEqual(await response,{offline:expected});}assert.deepEqual(matches,['/index.html','/player.html']);
 for(const url of ['/api/account','/api/project?share=abc','/api/world']){let handled=false;events.fetch({request:{method:'GET',url:'https://example.test'+url,mode:'cors'},respondWith:()=>handled=true});assert.equal(handled,false);}let foreign=false;events.fetch({request:{method:'GET',url:'https://blob.example.test/private.json',mode:'cors'},respondWith:()=>foreign=true});assert.equal(foreign,false);
});
test('public assets fetch current deployments first and fall back offline',async()=>{const {events,requests}=worker();let response;events.fetch({request:{method:'GET',url:'https://example.test/player.js',mode:'cors'},respondWith:p=>response=p});assert.deepEqual(await response,{offline:'/player.js'});assert.equal(requests.length,1);});
